export const ICON = {
  LOGO: "logo",
  DAY_MODE: "day-mode",
  NIGHT_MODE: "night-mode",
  GIT_HUB: "GitHub",
  GOOGLE: "Google",
  ACCOUNT: "account",
  ARCHIVE: "archive-outline",
  ARROW_DOUBLE_DOWN: "arrow-double-down",
  ARROW_DOWN: "arrow-down",
  ARROW_LEFT: "arrow-left",
  ARROW_RIGHT: "arrow-right",
  ARROW_LONG_1: "arrow-long-1",
  ARROW_LONG_2: "arrow-long-2",
  ARROW_ICONAMOON_SEND: "arrow-iconamoon-send", // фарбувати stroke
  CANCEL_IN_ROUND: "cancel-in-round",
  CHAT_ERROR_OUTLINE: "chat-error-outline",
  CHECK_BOX: "check-box",
  CHECK_BOX_GREEN: "check-box-green",
  CHECK_BOX_GRAY: "check-box-gray",
  CHECK_SMALL: "check-small",
  CHECK_BIG: "check-big",
  CLOSE_DEFAULT: "close-default",
  COPY: "copy",
  DELETE: "delete",
  DONATE: "donate",
  EDIT: "edit",
  EYE: "eye-outline",
  EYE_OFF: "eye-off-outline",
  FILTER: "filter", // фарбувати stroke
  FOLDER_OFF: "folder-off",
  FOLDER_OPEN: "folder-open",
  FOLDER: "folder",
  TABLER_BUCKET_GROUP: "tabler-bucket-group", // фарбувати stroke
  LOCATION_HOME: "location-home",
  LOCATION_REMOTE: "location-remote",
  LOCATION_HOME_WORK: "location-home-work",
  LOCATION_HYBRID: "location-hybrid",
  LOCATION_OFFICE: "location-office",
  LOG_OUT: "log-out",
  NOTE: "note",
  NOTIFICATION: "notification",
  PLUS: "plus",
  PLUS_GRAY: "plus-gray",
  SEARCH: "search",
  SETTINGS: "settings",
  STATISTICS: "statistics",
  VACANCY: "vacancy",
  VECTOR_CURVED_62: "vector-curved-62",
  VECTOR_CURVED_63: "vector-curved-63",
  DASHBOARD: "dashboard",
  GIRL_AND_DASHBOARD: "girl-and-dashboard",
  GIRL_WITH_PHONE: "girl-with-phone",
  MAN_AND_TIME: "man-and-time",
  SUPPORT: "support",
  RESTORE: "restore",
  BASELINE_MORE_HORIZ: "baseline-more-horiz",
  STAR: "star", // фарбувати stroke
  SEND: "send",
  SEND_GRAY: "send-gray",
  BURGER_MENU: "burger-menu",
  MAGE_FILTER: "mage-filter", // фарбувати і stroke, і fill
  PIN_FOR_CHROME: "pin-for-chrome",
} as const;

// export type IconId = keyof typeof ICON; // Тип для ключів ICON
export type IconId = (typeof ICON)[keyof typeof ICON]; // Тип для значень ICON
